import { ref } from 'vue'
import { invoke } from '@tauri-apps/api/core'
import type { PullRequest, Bookmark } from '../types'
import { computeRiskScore, riskLevel } from './useRiskScore'

/**
 * Composable for generating a formatted review summary from the current
 * PR's review state — checklist completion, bookmarks/annotations,
 * risk assessment, and time spent.
 */
export function useReviewSummary() {
  const summaryMarkdown = ref('')
  const posting = ref(false)
  const postError = ref<string | null>(null)

  /**
   * Generate a Markdown review summary from the current review state.
   */
  function generateSummary(opts: {
    pr: PullRequest
    checkedRules: Record<number, boolean>
    reviewRules: string[]
    bookmarks: Bookmark[]
    reviewElapsedSeconds: number
    filesReviewed?: number
    totalFiles?: number
  }): string {
    const { pr, checkedRules, reviewRules, bookmarks, reviewElapsedSeconds, filesReviewed, totalFiles } = opts
    const risk = computeRiskScore(pr)
    const level = riskLevel(risk)

    const lines: string[] = []
    lines.push(`## Review Summary — PR #${pr.number}`)
    lines.push('')
    lines.push(`**${pr.title}** by @${pr.author}`)
    lines.push('')

    // Risk assessment
    const riskEmoji = level === 'low' ? ':white_check_mark:' : level === 'medium' ? ':warning:' : level === 'high' ? ':x:' : ':rotating_light:'
    lines.push(`### Risk Assessment`)
    lines.push(`${riskEmoji} **${level.charAt(0).toUpperCase() + level.slice(1)}** (score: ${risk}/10)`)
    lines.push(`- ${pr.changed_files} files changed, +${pr.additions} / -${pr.deletions}`)
    lines.push('')

    // Checklist status
    if (reviewRules.length > 0) {
      const checkedCount = Object.values(checkedRules).filter(Boolean).length
      lines.push(`### Review Checklist (${checkedCount}/${reviewRules.length})`)
      for (let i = 0; i < reviewRules.length; i++) {
        const checked = checkedRules[i] ? 'x' : ' '
        lines.push(`- [${checked}] ${reviewRules[i]}`)
      }
      lines.push('')
    }

    // Annotations / bookmarks
    const unresolvedBookmarks = bookmarks.filter(b => !b.resolved)
    if (bookmarks.length > 0) {
      lines.push(`### Annotations (${unresolvedBookmarks.length} unresolved / ${bookmarks.length} total)`)
      for (const bm of bookmarks.slice(0, 10)) {
        const lineRef = bm.line_start != null ? `:${bm.line_start}` : ''
        const status = bm.resolved ? '~resolved~' : `**${bm.category}**`
        lines.push(`- \`${bm.file_path}${lineRef}\` — ${status}: ${bm.note || '(no note)'}`)
      }
      if (bookmarks.length > 10) {
        lines.push(`- _...and ${bookmarks.length - 10} more_`)
      }
      lines.push('')
    }

    // Files reviewed
    if (filesReviewed !== undefined && totalFiles !== undefined) {
      lines.push(`### Files Reviewed`)
      lines.push(`${filesReviewed} of ${totalFiles} files reviewed`)
      lines.push('')
    }

    // Time spent
    if (reviewElapsedSeconds > 0) {
      const mins = Math.floor(reviewElapsedSeconds / 60)
      const secs = reviewElapsedSeconds % 60
      lines.push(`### Time Spent`)
      lines.push(`${mins}m ${secs}s`)
      lines.push('')
    }

    lines.push('---')
    lines.push('_Generated by [Fuse](https://github.com/stuntrocket/fuse) — PR Review Companion_')

    const md = lines.join('\n')
    summaryMarkdown.value = md
    return md
  }

  /**
   * Copy the generated summary to the clipboard.
   */
  async function copyToClipboard(): Promise<boolean> {
    try {
      await navigator.clipboard.writeText(summaryMarkdown.value)
      return true
    } catch {
      return false
    }
  }

  /**
   * Post the generated summary as a comment on the PR via gh CLI.
   */
  async function postToGitHub(prId: number): Promise<boolean> {
    posting.value = true
    postError.value = null
    try {
      await invoke('post_review_summary', { prId, body: summaryMarkdown.value })
      return true
    } catch (e) {
      postError.value = String(e)
      return false
    } finally {
      posting.value = false
    }
  }

  return {
    summaryMarkdown,
    posting,
    postError,
    generateSummary,
    copyToClipboard,
    postToGitHub,
  }
}
